#!/usr/bin/env python3
"""
Generate iOS-specific options files for Vim 9.1

This script processes optiondefs.h and generates:
1. An iOS section for optiondefs.h with NULL var pointers
2. An options_init.h file for runtime initialization
"""

import re
import sys

def parse_optiondefs(filepath):
    """Parse optiondefs.h and extract option definitions."""
    with open(filepath, 'r') as f:
        content = f.read()

    # Find the options array section
    # Look for the start of the options array
    start_match = re.search(r'static __thread struct vimoption options\[\] =\s*\{', content)
    if not start_match:
        print("Could not find options array start", file=sys.stderr)
        return None, None, None

    array_start = start_match.end()

    # Find the end marker
    end_match = re.search(r'// end marker\s*\{NULL, NULL, 0,.*?\}\s*\};', content[array_start:])
    if not end_match:
        print("Could not find end marker", file=sys.stderr)
        return None, None, None

    array_end = array_start + end_match.end()
    options_section = content[array_start:array_end]

    return content[:start_match.start()], options_section, content[array_end:]

def nullify_var_pointers(options_section):
    """Replace (char_u *)&p_* with (char_u *)NULL for iOS."""
    # Pattern to match var pointers like (char_u *)&p_aleph
    # But keep VAR_WIN, NULL, and numeric values
    result = options_section

    # Replace &p_* variable references with NULL
    result = re.sub(r'\(char_u \*\)&p_\w+', '(char_u *)NULL', result)

    # Also handle &T_* terminal variable references
    result = re.sub(r'\(char_u \*\)&T_\w+', '(char_u *)NULL', result)

    return result

def generate_options_init(options_section):
    """Generate options_init.h for runtime initialization."""
    lines = []
    lines.append('/* vi:set ts=8 sts=4 sw=4 noet:')
    lines.append(' *')
    lines.append(' * options_init.h: Runtime initialization of options[] for iOS')
    lines.append(' *')
    lines.append(' * This file is auto-generated. Do not edit manually.')
    lines.append(' * Generated by generate_ios_options.py')
    lines.append(' */')
    lines.append('')
    lines.append('// iOS: re-initialize options[] with proper var pointers')
    lines.append('// This is needed because TLS variable addresses cannot be')
    lines.append('// compile-time constants in static initializers.')
    lines.append('')

    # Parse each option and generate assignment
    # Look for option definitions
    option_pattern = re.compile(
        r'\{\"(\w+)\".*?SCTX_INIT\}',
        re.DOTALL
    )

    # We need to find each option block and extract the var field
    # This is complex due to nested #ifdefs

    # Simpler approach: find lines with &p_* or &T_* and their option name
    current_lines = options_section.split('\n')
    option_index = 0
    current_option = None

    for i, line in enumerate(current_lines):
        # Check if this line starts a new option
        name_match = re.search(r'\{"(\w+)"', line)
        if name_match:
            current_option = name_match.group(1)

        # Check for var pointer assignment
        var_match = re.search(r'\(char_u \*\)&(p_\w+|T_\w+)', line)
        if var_match and current_option:
            var_name = var_match.group(1)
            # Check for conditional
            # Look back for #ifdef
            in_ifdef = False
            ifdef_condition = None
            for j in range(i-1, max(0, i-5), -1):
                if '#ifdef' in current_lines[j] or '#if ' in current_lines[j]:
                    ifdef_match = re.search(r'#if(?:def)?\s+(.+)', current_lines[j])
                    if ifdef_match:
                        ifdef_condition = ifdef_match.group(1).strip()
                        in_ifdef = True
                    break
                if '#else' in current_lines[j]:
                    # We're in an else block, need to negate
                    for k in range(j-1, max(0, j-10), -1):
                        if '#ifdef' in current_lines[k] or '#if ' in current_lines[k]:
                            ifdef_match = re.search(r'#if(?:def)?\s+(.+)', current_lines[k])
                            if ifdef_match:
                                ifdef_condition = '!' + ifdef_match.group(1).strip()
                                if ifdef_condition.startswith('!!'):
                                    ifdef_condition = ifdef_condition[2:]
                                elif ifdef_condition.startswith('!'):
                                    ifdef_condition = ifdef_condition[1:]
                                else:
                                    ifdef_condition = '!' + ifdef_condition
                                in_ifdef = True
                            break
                    break

            if in_ifdef and ifdef_condition:
                lines.append(f'#if {ifdef_condition}')
                lines.append(f'    // {current_option}')
                lines.append(f'    findoption_and_set_var("{current_option}", (char_u *)&{var_name});')
                lines.append('#endif')
            else:
                lines.append(f'    // {current_option}')
                lines.append(f'    findoption_and_set_var("{current_option}", (char_u *)&{var_name});')

    # Add helper function at start
    helper = '''
// Helper function to find option and set its var pointer
static void findoption_and_set_var(char *name, char_u *var)
{
    int idx = findoption((char_u *)name);
    if (idx >= 0)
        options[idx].var = var;
}

'''

    lines.insert(12, helper)

    return '\n'.join(lines)

def main():
    optiondefs_path = '/Users/kit/Development/vim9_ios/src/optiondefs.h'

    print("Parsing optiondefs.h...")
    prefix, options_section, suffix = parse_optiondefs(optiondefs_path)

    if options_section is None:
        print("Failed to parse optiondefs.h")
        return 1

    print(f"Found options section ({len(options_section)} chars)")

    # Generate iOS version with NULL var pointers
    ios_options = nullify_var_pointers(options_section)

    # Write the modified optiondefs.h with iOS conditional
    print("Writing modified optiondefs.h...")
    with open(optiondefs_path, 'w') as f:
        f.write(prefix)
        f.write('static __thread struct vimoption options[] =\n')
        f.write('#if !TARGET_OS_IPHONE\n')
        f.write('{')
        f.write(options_section)
        f.write('\n#else // TARGET_OS_IPHONE\n')
        f.write('// iOS: var pointers are NULL at compile time, set at runtime via options_init.h\n')
        f.write('{')
        f.write(ios_options)
        f.write('\n#endif // TARGET_OS_IPHONE\n')
        f.write(suffix)

    # Generate options_init.h
    print("Generating options_init.h...")
    options_init = generate_options_init(options_section)

    with open('/Users/kit/Development/vim9_ios/src/options_init.h', 'w') as f:
        f.write(options_init)

    print("Done!")
    return 0

if __name__ == '__main__':
    sys.exit(main())
